### PR TITLE
Change indicator bound with bounds tuple

### PR DESCRIPTION
**Pull request by dreinon**

### CODE REVIEW

**Comment by dreinon** [comment]
Related to conversation: https://github.com/tpaviot/ProcessScheduler/pull/67#discussion_r649206948_

**Comment by tpaviot** [comment]
Azure build has failed with error
```bash
  File "/home/vsts/work/1/s/processscheduler/objective.py", line 28, in Indicator
    bounds: Optional[tuple[Optional[int]]] = None) -> None:
TypeError: 'type' object is not subscriptable
```

**Comment by dreinon** [comment]
My bad. I'm travelling to Barcelona today so I'll check it out tonight.

**Comment by dreinon** [comment]
> My bad. I'm travelling to Barcelona today so I'll check it out tonight.

I don't know if you can change it, but the problem comes from `tuple` being the standard python type (subscriptable sincr python 3. ¿9?) This has to be modified  with `Tuple` type from typing library.

So it's actually just changing t to Uppercase and import Tuple from typing if not done already.

**Comment by tpaviot** [comment]
Committing changes from your mobile phone? I  never reached such a damn reactivity!

**Comment by dreinon** [comment]
Lol haha it was just 1 letter

**Comment by dreinon** [comment]
Can you merge max-utilization with master?

**Pull request merged**
