### PR TITLE
Update doc

### PR DESCRIPTION
**Pull request by dreinon**

### CODE REVIEW

**Comment by dreinon** [comment]
Solving still left to review.

**Comment by tpaviot** [comment]
The ``not_`` change has to be propagated to the related unit tests. I'm updating the solver doc in the meantime

**Comment by dreinon** [comment]
Right, forgot to do that.

I'll do it later

**Comment by tpaviot** [comment]
Solving reviewed.

Can you please rebase your branch on top of update-doc?

**Comment by dreinon** [comment]
Sure

**Comment by dreinon** [comment]
Have I rebased correctly?

**Comment by tpaviot** [comment]
@dreinon yep, rebase successful. Did you fix the tests?

**Comment by dreinon** [comment]
yes, I fixed my fix of not not operator, since I had done it wrong. After that, tests passed.

**Comment by tpaviot** [comment]
👍

**Pull request merged**
