### PR TITLE
Flowtime single resource

### PR DESCRIPTION
**Pull request by tpaviot**
Related to issue #50 

to use:
```python
problem.add_objective_flowtime_single_resource(worker_1, time_interval = [40, 50])
```

### CODE REVIEW

**Comment by dreinon** [comment]
Would this already work for time intervals :open_mouth: ?

**Comment by tpaviot** [comment]
Currently only for one single time interval. You cannot pass a list of time intervals. And I did not test to add multiple single intervals, for example:
```python
problem.add_objective_flowtime_single_resource(worker_1, time_interval = [40, 50])
problem.add_objective_flowtime_single_resource(worker_1, time_interval = [60, 70])
```

**Comment by dreinon** [comment]
Well still a big progress!! Thanks you!

**Comment by tpaviot** [comment]
This needs to be tested but I merge the branch. I think this implementation is not efficient in terms of computing time, we'll see later for any improvement, let's first check the expected behavior is correct.

**Comment by dreinon** [comment]
Since this is finally an objective, its API for many time intervals would be add many objectives right? About what you were saying about performance, I wonder if this volume of objectives would enlarge the problem too much. In my case, I would have to add:
 - 1 objective/(time_interval*resource) * 7 time_intervals * 20 resources = 140 objectives
I can try it out though and see how it works! Other possibility is to first test it before applying it to my problem, so I could also make some tests.

Also, I wonder if this would currently work in the new multiobjective incremental solver, with other max objective like utilization, since these flowtime_single_resource are min objectives right?

Thank you!

**Comment by tpaviot** [comment]
Ok, let me know about your tests. I ran a few tests with the new multiobjective incremental solver, it's much more convenient than the previous optimizer.

**Comment by dreinon** [comment]
Nice! Although with much more convinient, you mean it might be duable to have 140 objectives?
And also, is the new solver already compatible with mixed max and min objectives? (to make tests mixing them)

**Comment by tpaviot** [comment]
Don't know what it gives with so many objectives, you should test (first try with 2, 4, 10, before trying 140!). The new multi-objective solver can deal with both min/max objectives (see last commit fb64fff).

**Comment by dreinon** [comment]
Yes of course, I'll start simple haha. Thanks!

**Pull request merged**
